INCLUDE(CheckIncludeFileCXX)
INCLUDE(CheckSymbolExists)
INCLUDE(CheckCXXSymbolExists)
INCLUDE(CheckLibraryExists)

CHECK_INCLUDE_FILE_CXX(dlfcn.h HAVE_DLFCN_H)
if( HAVE_DLFCN_H )
    ADD_DEFINITIONS(-DHAVE_DLFCN_H)
ENDIF()

CHECK_INCLUDE_FILE_CXX(ext/slist HAVE_EXT_SLIST)
if( HAVE_EXT_SLIST )
    ADD_DEFINITIONS(-DHAVE_EXT_SLIST)
ENDIF()

CHECK_INCLUDE_FILE_CXX(inttypes.h HAVE_INTTYPES_H)
if( HAVE_INTTYPES_H )
    ADD_DEFINITIONS(-DHAVE_INTTYPES_H)
ENDIF()

CHECK_SYMBOL_EXISTS(getopt unistd.h HAVE_POSIX_GETOPT)
if( HAVE_LIBIBERTY_GETOPT )
    ADD_DEFINITIONS(-DHAVE_POSIX_GETOPT)
ENDIF()

CHECK_SYMBOL_EXISTS(getopt libiberty.h HAVE_LIBIBERTY_GETOPT)
if( HAVE_LIBIBERTY_GETOPT )
    ADD_DEFINITIONS(-DHAVE_LIBIBERTY_GETOPT)
ENDIF()

FIND_LIBRARY(HAVE_LIBINTL intl)
if( HAVE_LIBINTL )
    ADD_DEFINITIONS(-DHAVE_LIBINTL)
ENDIF()

CHECK_SYMBOL_EXISTS(localtime_r time.h HAVE_LOCALTIME_R)
if( HAVE_LOCALTIME_R )
    ADD_DEFINITIONS(-DHAVE_LOCALTIME_R)
ENDIF()

CHECK_INCLUDE_FILE_CXX(memory.h HAVE_MEMORY_H)
if( HAVE_MEMORY_H )
    ADD_DEFINITIONS(-DHAVE_MEMORY_H)
ENDIF()

CHECK_SYMBOL_EXISTS(getopt unistd.h HAVE_LIBIBERTY_GETOPT)
if( HAVE_LIBIBERTY_GETOPT )
    ADD_DEFINITIONS(-DHAVE_LIBIBERTY_GETOPT)
ENDIF()

FIND_LIBRARY(HAVE_PTHREAD pthread)
if( HAVE_PTHREAD )
    ADD_DEFINITIONS(-DHAVE_PTHREAD)
ENDIF()

CHECK_INCLUDE_FILE_CXX(stdint.h HAVE_STDINT_H)
if( HAVE_STDINT_H )
    ADD_DEFINITIONS(-DHAVE_STDINT_H)
ENDIF()

CHECK_INCLUDE_FILE_CXX(stdlib.h HAVE_STDLIB_H)
if( HAVE_STDLIB_H )
    ADD_DEFINITIONS(-DHAVE_STDLIB_H)
ENDIF()

CHECK_CXX_SYMBOL_EXISTS(std::slist container slist HAVE_STD_SLIST)
if( HAVE_STD_SLIST )
    ADD_DEFINITIONS(-DHAVE_STD_SLIST)
ENDIF()

CHECK_INCLUDE_FILE_CXX(strings.h HAVE_STRINGS_H)
if( HAVE_STRINGS_H )
    ADD_DEFINITIONS(-DHAVE_STRINGS_H)
ENDIF()

CHECK_INCLUDE_FILE_CXX(string.h HAVE_STRING_H)
if( HAVE_STRING_H )
    ADD_DEFINITIONS(-DHAVE_STRING_H)
ENDIF()

CHECK_INCLUDE_FILE_CXX(synch.h HAVE_SYNCH_H)
if( HAVE_SYNCH_H )
    ADD_DEFINITIONS(-DHAVE_SYNCH_H)
ENDIF()

CHECK_INCLUDE_FILE_CXX(sys/stat.h HAVE_SYS_STAT_H)
if( HAVE_SYS_STAT_H )
    ADD_DEFINITIONS(-DHAVE_SYS_STAT_H)
ENDIF()

CHECK_INCLUDE_FILE_CXX(sys/types.h HAVE_SYS_TYPES_H)
if( HAVE_SYS_TYPES_H )
    ADD_DEFINITIONS(-DHAVE_SYS_TYPES_H)
ENDIF()

CHECK_INCLUDE_FILE_CXX(unistd.h HAVE_UNISTD_H)
if( HAVE_UNISTD_H )
    ADD_DEFINITIONS(-DHAVE_UNISTD_H)
ENDIF()

CHECK_INCLUDE_FILE_CXX("mysql/mysql.h" MYSQLPP_MYSQL_HEADERS_BURIED)
if( MYSQLPP_MYSQL_HEADERS_BURIED )
    ADD_DEFINITIONS(-DMYSQLPP_MYSQL_HEADERS_BURIED)
ENDIF()

#DEFINE_PROPERTY(GLOBAL STDC_HEADERS)